config/routes.rb
Rails.application.routes.draw do
  resources :journals do
    member  do
      delete :delete_journal_file_attachment
    end
    resources :articles
  end
  resources :banks
  resources :payments do
    collection do
      put :set_approve
    end
    member do
      get :approve
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subject_plans do
    member do
      put :approve_one
      put :print
      get :print_sp
    end
    collection do
      put :set_approve
    end
  end
  get 'tahun_akademik', to: 'academics#tahun_akademik', as: :tahun_akademik
  resources :academics
  resources :candidate_students
  resources :item_accreditations
  resources :authenticate_phones, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  get 'index_skripsi', to: 'essays#index_skripsi', as: :index_skripsi
  resources :essays

  get 'index_buku', to: 'book_collections#index_buku', as: :index_buku
  resources :book_collections

  get 'index_surat', to: 'studentletters#index_surat', as: :index_surat
  resources :studentletters
  resources :jenjang_didiks

  get 'kabar_teknik', to: 'campus_newspapers#kabar_teknik', as: :kabar_teknik
  resources :campus_newspapers
  resources :landing_pages, only: [:index]



  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  # resources :mahasiswas do
  #   collection do
  #     put :
  #   end
  # end


  get 'daftar_calon_mahasiswa', to: 'dashboards#daftar_calon_mahasiswa', as: "daftar_calon_mahasiswa"

  get 'buat_semester_genap', to: 'academic_years#buat_semester_genap', as: "buat_semester_genap"
  get 'buat_semester_ganjil', to: 'academic_years#buat_semester_ganjil', as: "buat_semester_ganjil"

  get 'token_session', :to => "sessions#new"
  post 'token_session', :to => "sessions#create"
  get 'token_session_out', :to => "sessions#destroy"



  get 'token', to: 'graduates#token', as: "token"
  get 'wisudawan', to: 'graduates#wisudawan', as: "wisudawan"
  get 'semua', to: 'graduates#semua', as: "semua"
  get 'galeri', to: 'graduates#galeri', as: "galeri"
  get 'buku', to: 'graduates#buku', as: "buku"

  get 'index_dosen', to: 'dummy_lectures#index_dosen', as: "index_dosen"
  resources :dummy_lectures
  resources :academic_years

  get 'jadwal_kuliah', to: 'pages#jadwal_kuliah', as: "jadwal_kuliah"
  resources :schedule_subjects

  resources :subjects

  get 'info', to: 'pages#info', as: "info"

  get 'kalendar_akademik', to: 'pages#kalendar_akademik', as: "kalendar_akademik"
  get 'daftar', to: 'pages#daftar', as: "daftar"

  get 'akreditasi', to: 'item_accreditations#index', as: "akreditasi"

  concern :documentable do
    resources :documents, only: [:new, :create, :edit, :update, :destroy]
  end
  concern :dashboardtable do
    # authenticated :user do
    #   root to: 'dashboards#index'#, as: :authenticated_root
      resources :dashboards, only: [:index]
    # end
  end

  namespace :juniors do
    concerns :dashboardtable
  end

  namespace :staffs do
    concerns :dashboardtable
  end

  namespace :students do
    concerns :dashboardtable
  end

  namespace :lectures do
    concerns :dashboardtable
  end

  namespace :admins do
    concerns :dashboardtable
  end

  resources :lectures, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :profile
      get :educations
      get :training_professionals
      get :teachings
      get :materials
      get :researchs
      get :scientifics
      get :papers
      get :reviewers
      get :conferences
      get :professionals
      get :positions
      get :student_organizations
      get :scientific_organizations
      get :appreciations
      put :print
    end
      resources :lecture_education_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :professional_trainings, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_materials, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_researches, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientific_works, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_papers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_reviewers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_conferences, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_position_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_professional_activities, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_student_organization_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_appreciations, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientist_organizations, only:[:index, :new, :create, :edit, :update, :destroy]
  end

  resources :students, only:[:index, :show, :edit, :update, :destroy], concerns: :documentable do
    member do
      get :edit_formulir
      patch :make
      get :delete_file
      # p :print
      get :print_blanko
      get :print_formulir
      put :active_one
    end
    collection do
      get :studyplans
      put :active_all
    end

    resources :payments, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        get :print
        get :print_registrasi
        get :letter
      end
    end
  end

  resources :staffs , only:[:index, :show, :new, :create,  :edit, :update, :destroy ] do
    member do
      get :profile
    end
  end


  resources :lecture_lists
  resources :graduates do
    collection  do
      put :update_all
      post :import
    end
    member do
      get :download
      get :send_token_email
      get :formulir_wisuda
      get :edit_formulir
      patch :update_access_token, to:'graduates#update_access_token'
    end
  end

  resources :mahasiswas do
    member do
      get 'biodata', to: 'mahasiswas#biodata', as: :biodata
      get 'edit_biodata', to: 'mahasiswas#edit_biodata', as: :edit_biodata
    end
    collection do
      put :activate
    end
    resources :documents

  end

  get 'index_mahasiswa', to: 'mahasiswa_profiles#index_mahasiswa', as: :index_mahasiswa
  resources :mahasiswa_profiles

  root to: 'pages#index'

  devise_for :users, controllers: {
        passwords: 'users/passwords',
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'}

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage
    # for speed, so on the client side we'll upload files to our app.
    mount Shrine.upload_endpoint(:cache) => "/upload"
  end
end

app/models/staff.rb
# == Schema Information
#
# Table name: users
#
#  id                         :bigint(8)        not null, primary key
#  email                      :string           default(""), not null
#  encrypted_password         :string           default(""), not null
#  reset_password_token       :string
#  reset_password_sent_at     :datetime
#  remember_created_at        :datetime
#  sign_in_count              :integer          default(0), not null
#  current_sign_in_at         :datetime
#  last_sign_in_at            :datetime
#  current_sign_in_ip         :inet
#  last_sign_in_ip            :inet
#  confirmation_token         :string
#  confirmed_at               :datetime
#  confirmation_sent_at       :datetime
#  unconfirmed_email          :string
#  failed_attempts            :integer          default(0), not null
#  unlock_token               :string
#  locked_at                  :datetime
#  image_data                 :text
#  type                       :string
#  provider                   :string
#  uid                        :string
#  name                       :string
#  birth_date                 :date
#  birth_place                :string
#  gender                     :string
#  religion                   :string
#  marital_status             :string
#  hobby                      :string
#  stambuk                    :string
#  is_student                 :boolean          default(FALSE)
#  is_graduate                :boolean
#  is_lecture                 :boolean
#  is_staff                   :boolean
#  access_token               :string
#  nidn                       :string
#  nip                        :string
#  dummy_lecture_1_id         :bigint(8)
#  dummy_lecture_2_id         :bigint(8)
#  major_id                   :bigint(8)
#  faculty_id                 :bigint(8)
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  blangko_data               :text
#  academic_year_id           :integer
#  sortlist                   :integer
#  is_active                  :boolean          default(TRUE)
#  phone_number               :string
#  authy_id                   :string
#  last_sign_in_with_authy    :datetime
#  authy_enabled              :boolean          default(FALSE)
#  is_phone_verified          :boolean          default(FALSE)
#  is_alumni                  :boolean          default(FALSE)
#  religion_id                :bigint(8)
#  lecture_functional_type_id :bigint(8)
#  referral                   :string
#
# Indexes
#
#  index_users_on_access_token                (access_token) UNIQUE
#  index_users_on_authy_id                    (authy_id)
#  index_users_on_confirmation_token          (confirmation_token) UNIQUE
#  index_users_on_dummy_lecture_1_id          (dummy_lecture_1_id)
#  index_users_on_dummy_lecture_2_id          (dummy_lecture_2_id)
#  index_users_on_email                       (email) UNIQUE
#  index_users_on_faculty_id                  (faculty_id)
#  index_users_on_lecture_functional_type_id  (lecture_functional_type_id)
#  index_users_on_major_id                    (major_id)
#  index_users_on_nidn                        (nidn) UNIQUE
#  index_users_on_religion_id                 (religion_id)
#  index_users_on_reset_password_token        (reset_password_token) UNIQUE
#  index_users_on_stambuk                     (stambuk) UNIQUE
#  index_users_on_unlock_token                (unlock_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (lecture_functional_type_id => lecture_functional_types.id)
#  fk_rails_...  (religion_id => religions.id)
#

class Staff < User
  belongs_to :religion, optional: true
  belongs_to :major, optional: true
  has_one :staff_profile, dependent: :destroy
  has_one :alamat_tinggal, foreign_key: :user_id, class_name: "Address"
  has_one_attached :staff_photo_file
  accepts_nested_attributes_for :staff_profile, reject_if: proc{|a| a[:nama].blank?}, allow_destroy: true
  accepts_nested_attributes_for :alamat_tinggal, reject_if: proc{|a| a[:street].blank?}, allow_destroy: true

  def is_active?
    self.is_active == true ? "Aktif" : "Tidak Aktif"
  end

  def generate_access_token
    self.regenerate_access_token
  end


  def self.authenticate_staff_token(staff, access_token)
    if staff && staff.access_token == access_token
      staff
    else
      nil
    end
  end

end

app/controllers/staffs/base_controller.rb
class Staffs::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :checking_staff!
  #
  private
  def checking_staff!
    redirect_to send("#{user_base_url.pluralize}_dashboards_path"), flash: { error: 'Anda tidak memiliki akses ke halaman ini' } if !current_user.is_staff?
  end
end

app/controllers/staffs/dashboards_controller.rb
class Staffs::DashboardsController < Staffs::BaseController
  def index
    @campus_newspapers = CampusNewspaper.where(terbit: true).order("created_at desc" )
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_user!
  def active_one
    @staff = Staff.find(params[:id])
    if @staff.is_active == false
      @staff.update(is_active: true)
      redirect_to staffs_path, notice: "Berhasil diaktifkan"
    elsif @staff.is_active == true
      @staff.update(is_active: false)
      redirect_to staffs_path, notice: "Berhasil digagalkan"
    elsif @staff.is_active == nil
      @staff.update(is_active: true)
      redirect_to staffs_path, notice: "Berhasil diaktifkan"
    end
  end

  def active_all
    if params[:commit] == "Semua Aktif"
      @staffs = Staff.where(id: params[:staff_id]).update_all(is_active: true)
      redirect_to staffs_path, notice: "Berhasil Aktif"
    elsif params[:commit] == "Semua Tidak Aktif"
      @staffs = Staff.where(id: params[:staff_id]).update_all(is_active: false)
      redirect_to staffs_path, notice: "Berhasil Tidak Aktif"
    end
  end

  def index
    # @staffs = StaffProfile.order(sort_column + " " + sort_direction)
    @staffs = Staff.where("created_at > ?", "01 Jan 2020").includes(:major).order(sort_column + " " + sort_direction).page(params[:page]).per(20)
    @staffs = @staffs.staff_search(params[:staff_search]) if params[:staff_search]
    respond_to do |format|
      format.html
      format.js
    end
  end


  def sort_column
    params[:sort] || 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def edit_formulir
    @staff = Staff.find(params[:id])
  end

  def edit
    @staff = Staff.find(params[:id])
    @staff.build_staff_profile unless @staff.staff_profile.present?
    @staff.build_alamat_tinggal unless @staff.alamat_tinggal.present?
  end

  def update
    @staff = Staff.find(params[:id])
    respond_to do |format|
      if @staff.update!(staff_params)
        if @staff.is_active?
          format.html{redirect_to staff_path(@staff), notice: "Data Berhasil Diperbarui"}
        elsif @staff.is_not_active?
          format.html{redirect_to edit_staff_path(@staff), notice: "Data Calon Mahasiswa Berhasil Diperbarui"}
        else
          format.html{redirect_to staff_path(@staff), notice: "Data mahasiswa Berhasil Diperbarui"}
        end
      else
        format.html{redirect_to edit_staff_path(@staff), notice: "Data Gagal Diperbarui"}
      end
    end
  end

  def show
    if current_user.is_staff?
      @staff = Staff.find(params[:id])
    else
      @staff = Staff.find(params[:id])
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    if @staff.destroy
      redirect_to staffs_path, notice: "Data berhasil dihapus"
    end
  end

  def staff_params
    params.require(:staff).permit(
      :major_id,
      :staff_photo_file,
      :religion_id,
      staff_profile_attributes:[
       :id,
       :nama,
       :gelar_depan_nama,
       :gelar_belakang_nama,
       :nomor_induk_pegawai,
       :nomor_induk_dosen_negara,
       :nomor_induk_kependudukan,
       :jenis_kelamin,
       :tempat_lahir,
       :tanggal_lahir,
       :lecture_type,
       :status,
       :status_perkawinan,
       :handphone,
       :kewarganegaraan,
       :_destroy
     ],
     alamat_tinggal_attributes:[
       :id,
       :street,
       :rt,
       :rw,
       :kelurahan,
       :kecamatan,
       :city,
       :province,
       :post_code,
       :_destroy
     ]
    )
  end
end

app/views/staffs/_form.html.erb
<%= simple_nested_form_for @staff, url: staff_path(@staff), method: :put, wrapper: :default do |f| %>
<%= render "shared/errors", object: @staff %>
<div class="card">
  <div class="card-header has-background-white-ter">
    <div class="card-header-title">
      Biodata Staf
    </div>
  </div>
  <div class="card-content">
    <div class="card">
      <div class="card-content has-background-white-ter">
        <%= f.simple_fields_for :staff_profile do |staff_profile| %>
          <%= render partial: 'staffs/form/profile', locals:{staff: f, staff_profile: staff_profile} %>
        <% end %>
        <%= f.simple_fields_for :alamat_tinggal do |address| %>
          <%= render partial: 'staffs/form/address', locals:{f: f, address: address} %>
        <% end %>
      </div>
  </div>
  <div class="card-content">
      <div class="buttons is-right">
        <%= f.submit "Simpan", class:'button is-primary is-small'  %>
        <%= link_to "Kembali", staff_path(@staff), class: 'button is-danger is-small' %>
      </div>
  </div>
</div>
<% end %>

app/views/staffs/edit.html.erb
<%= render 'form' %>

app/views/staffs/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 mb-3">
      <div class="card">
        <div class="card-header">
          <h5>Daftar Staf Pegawai Fakultas Teknik UPRI</h5>
        </div>
        <div class="card-body">
          <%= link_to 'Tambah staf', new_staff_path, class: "btn btn-success mb-2" %>
          <%= form_tag activate_staffs_path, method: :put do %>
          <table class="table table-sm table-bordered ">
            <thead>
              <tr>
                <th class="text-center">NO</th>
                <th >EMAIL</th>
                <th class="text-center">TGL DAFTAR</th>
                <th>STATUS</th>
                <th colspan="2">AKSI</th>
              </tr>
            </thead>

            <tbody>
              <% if params[:page].nil? || params[:page]== "0" || params[:page]=="1" %>
                <% x = 0 %>
              <% else %>
                <% page = params[:page].to_i - 1 %>
                <% x = page*10 %>
              <% end %>
              <% @staffs.each_with_index do |staf, i| %>
                <tr>
                  <td class="text-center"><%= i = i + x + 1 %></td>
                  <td><%= staf.email %></td>
                  <td class="text-center"><%= staf.created_at.strftime("%d-%m-%Y") %></td>
                  <td><%= staf.is_active? %></td>
                  <td><%= check_box_tag 'staf_id[]', staf.id %></td>
                  <td><%= link_to icon_edit(''), "#" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= submit_tag "Status Aktif" %><%= submit_tag "Hapus Semua" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 text-center mb-5">
      <%= paginate  @staffs %>
    </div>
  </div>
</div>

app/views/staffs/profile.html.erb
<section class="section">
    <div class="columns">
        <div class="column">
            <div class="card">
              <%= simple_nested_form_for @staff, url: staff_path(@staff), method: :put, wrapper: :default, defaults: { wrapper: false }  do |f| %>
              <div class="card-content">
                <h3>Profil Anda</h3>
                  <%= f.simple_fields_for :staff_profile do |staff_profile| %>
                    <%= staff_profile.input :nama %>
                    <%= staff_profile.input :gelar_depan_nama %>
                    <%= staff_profile.input :gelar_belakang_nama %>
                    <%= staff_profile.input :nomor_induk_pegawai %>
                    <%= staff_profile.input :jenis_kelamin, collection: ["laki-laki", "perempuan"], include_blank: false %>
                    <%= staff_profile.input :tempat_lahir %>
                    <%= staff_profile.input :tanggal_lahir %>
                    <%= staff_profile.input :nomor_pokok_wajib_pajak %>
                    <%= staff_profile.input :status %>
                  <% end %>
                </div>
                <div class="buttons card-footer-item is-right">
                  <%= f.submit "Simpan", class:'button is-primary'  %>
                  <%= link_to "Kembali", staff_path(@staff), class: 'button is-danger' %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/staffs/show.html.erb
<div class="card">
  <div class="card-header has-background-white-ter">
    <div class="card-header-title">
      Profil Staff
    </div>
    <div class="card-header-icon">
      <%= link_to icon_edit(''), edit_staff_path(@staff), class:'button is-danger is-small'  %>
    </div>
  </div>
  <% if @staff.staff_profile.present?  %>
  <div class="card-content">
    <div class="columns">
      <div class="column is-3">
        <div class="card">
          <div class="card-image">
            <figure class="image" width="354px" >
              <%= active_storage_file(@staff.staff_photo_file, "https://bulma.io/images/placeholders/1280x960.png", "354x472", "preview" ) %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4 has-text-centered"><%= @staff.staff_profile.try(:nama).upcase rescue nil %></p>
                <p class="subtitle is-6 has-text-centered"><%= @staff.staff_profile.try(:nomor_induk_pegawai) rescue nil %></p>
                <p class="subtitle is-6 has-text-centered"><%= @staff.major.faculty.name.titleize rescue nil %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="table-container">
          <table class="table is-hoverable is-striped is-bordered is-narrow is-fullwidth">
            <tbody>
              <tr>
                <th class="has-text-weight-light" width="200px">Nama</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.nama.titleize rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Nomor Induk Pegawai</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.try(:nomor_induk_pegawai) rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Program Studi</th>
                <th class="has-text-weight-light"><%= @staff.major.name rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Status Akun</th>
                <th class="has-text-weight-light"><%= @staff.is_active? ? "Aktif" : "Belum Aktif" rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Jenis Kelamin</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.try(:jenis_kelamin) rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Tempat, Tanggal Lahir</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.try(:tempat_lahir).titleize rescue nil %>&nbsp;<%= @staff.staff_profile.tanggal_lahir.strftime("%d-%m-%Y") rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Status Akademik</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.status rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Handphone</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.try(:handphone) rescue nil %></th>
              </tr>

              <tr>
                <th class="has-text-weight-light">Agama</th>
                <th class="has-text-weight-light"><%= @staff.try(:religion).name rescue nil %></th>
              </tr>
              <tr>
                <th class="has-text-weight-light">Kewarganegaraan</th>
                <th class="has-text-weight-light"><%= @staff.staff_profile.try(:kewarganegaraan) rescue nil %></th>
              </tr>

              <tr>
                <th class="has-text-weight-light">Alamat Tinggal</th>
                <th class="has-text-weight-light"><%= @staff.alamat_tinggal.try(:street) %>&nbsp;<%= "RT #{@staff.alamat_tinggal.try(:rt)}" %>&nbsp;<%= "RW #{@staff.alamat_tinggal.try(:rw)}" %>&nbsp;<%= "Kelurahan #{@staff.alamat_tinggal.try(:kelurahan)}" %>&nbsp;<%= "Kecamatan #{@staff.alamat_tinggal.try(:kecamatan)}" %>&nbsp;<%= "Kabupaten/Kota #{@staff.alamat_tinggal.try(:city)}" %>&nbsp;<%= "Propinsi #{@staff.alamat_tinggal.try(:province)}" %>&nbsp;<%= "Kodepos #{@staff.alamat_tinggal.try(:post_code)}"%></th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <% else %>
    <div class="card-content">
      Maaf belum ada data
    </div>
  <% end %>
</div>