config/routes.rb
Rails.application.routes.draw do
  resources :journals do
    member  do
      delete :delete_journal_file_attachment
    end
    resources :articles
  end
  resources :banks
  resources :payments do
    collection do
      put :set_approve
    end
    member do
      get :approve
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subject_plans do
    member do
      put :approve_one
      put :print
      get :print_sp
    end
    collection do
      put :set_approve
    end
  end
  get 'tahun_akademik', to: 'academics#tahun_akademik', as: :tahun_akademik
  resources :academics
  resources :candidate_students
  resources :item_accreditations
  resources :authenticate_phones, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  get 'index_skripsi', to: 'essays#index_skripsi', as: :index_skripsi
  resources :essays

  get 'index_buku', to: 'book_collections#index_buku', as: :index_buku
  resources :book_collections

  get 'index_surat', to: 'studentletters#index_surat', as: :index_surat
  resources :studentletters
  resources :jenjang_didiks

  get 'kabar_teknik', to: 'campus_newspapers#kabar_teknik', as: :kabar_teknik
  resources :campus_newspapers
  resources :landing_pages, only: [:index]



  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  # resources :mahasiswas do
  #   collection do
  #     put :
  #   end
  # end


  get 'daftar_calon_mahasiswa', to: 'dashboards#daftar_calon_mahasiswa', as: "daftar_calon_mahasiswa"

  get 'buat_semester_genap', to: 'academic_years#buat_semester_genap', as: "buat_semester_genap"
  get 'buat_semester_ganjil', to: 'academic_years#buat_semester_ganjil', as: "buat_semester_ganjil"

  get 'token_session', :to => "sessions#new"
  post 'token_session', :to => "sessions#create"
  get 'token_session_out', :to => "sessions#destroy"



  get 'token', to: 'graduates#token', as: "token"
  get 'wisudawan', to: 'graduates#wisudawan', as: "wisudawan"
  get 'semua', to: 'graduates#semua', as: "semua"
  get 'galeri', to: 'graduates#galeri', as: "galeri"
  get 'buku', to: 'graduates#buku', as: "buku"

  get 'index_dosen', to: 'dummy_lectures#index_dosen', as: "index_dosen"
  resources :dummy_lectures
  resources :academic_years

  get 'jadwal_kuliah', to: 'pages#jadwal_kuliah', as: "jadwal_kuliah"
  resources :schedule_subjects

  resources :subjects

  get 'info', to: 'pages#info', as: "info"

  get 'kalendar_akademik', to: 'pages#kalendar_akademik', as: "kalendar_akademik"
  get 'daftar', to: 'pages#daftar', as: "daftar"

  get 'akreditasi', to: 'item_accreditations#index', as: "akreditasi"

  concern :documentable do
    resources :documents, only: [:new, :create, :edit, :update, :destroy]
  end
  concern :dashboardtable do
    # authenticated :user do
    #   root to: 'dashboards#index'#, as: :authenticated_root
      resources :dashboards, only: [:index]
    # end
  end

  namespace :juniors do
    concerns :dashboardtable
  end

  namespace :staffs do
    concerns :dashboardtable
  end

  namespace :students do
    concerns :dashboardtable
  end

  namespace :lectures do
    concerns :dashboardtable
  end

  namespace :admins do
    concerns :dashboardtable
  end

  resources :lectures, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :profile
      get :educations
      get :training_professionals
      get :teachings
      get :materials
      get :researchs
      get :scientifics
      get :papers
      get :reviewers
      get :conferences
      get :professionals
      get :positions
      get :student_organizations
      get :scientific_organizations
      get :appreciations
      put :print
    end
      resources :lecture_education_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :professional_trainings, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_materials, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_researches, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientific_works, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_papers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_reviewers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_conferences, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_position_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_professional_activities, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_student_organization_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_appreciations, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientist_organizations, only:[:index, :new, :create, :edit, :update, :destroy]
  end

  resources :students, only:[:index, :show, :edit, :update, :destroy], concerns: :documentable do
    member do
      get :edit_formulir
      patch :make
      get :delete_file
      # p :print
      get :print_blanko
      get :print_formulir
      put :active_one
    end
    collection do
      get :studyplans
      put :active_all
    end

    resources :payments, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        get :print
        get :print_registrasi
        get :letter
      end
    end
  end

  resources :staffs , only:[:index, :show, :new, :create,  :edit, :update, :destroy ] do
    member do
      get :profile
    end
  end


  resources :lecture_lists
  resources :graduates do
    collection  do
      put :update_all
      post :import
    end
    member do
      get :download
      get :send_token_email
      get :formulir_wisuda
      get :edit_formulir
      patch :update_access_token, to:'graduates#update_access_token'
    end
  end

  resources :mahasiswas do
    member do
      get 'biodata', to: 'mahasiswas#biodata', as: :biodata
      get 'edit_biodata', to: 'mahasiswas#edit_biodata', as: :edit_biodata
    end
    collection do
      put :activate
    end
    resources :documents

  end

  get 'index_mahasiswa', to: 'mahasiswa_profiles#index_mahasiswa', as: :index_mahasiswa
  resources :mahasiswa_profiles

  root to: 'pages#index'

  devise_for :users, controllers: {
        passwords: 'users/passwords',
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'}

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage
    # for speed, so on the client side we'll upload files to our app.
    mount Shrine.upload_endpoint(:cache) => "/upload"
  end
end

app/models/student.rb
# == Schema Information
#
# Table name: users
#
#  id                         :bigint(8)        not null, primary key
#  email                      :string           default(""), not null
#  encrypted_password         :string           default(""), not null
#  reset_password_token       :string
#  reset_password_sent_at     :datetime
#  remember_created_at        :datetime
#  sign_in_count              :integer          default(0), not null
#  current_sign_in_at         :datetime
#  last_sign_in_at            :datetime
#  current_sign_in_ip         :inet
#  last_sign_in_ip            :inet
#  confirmation_token         :string
#  confirmed_at               :datetime
#  confirmation_sent_at       :datetime
#  unconfirmed_email          :string
#  failed_attempts            :integer          default(0), not null
#  unlock_token               :string
#  locked_at                  :datetime
#  image_data                 :text
#  type                       :string
#  provider                   :string
#  uid                        :string
#  name                       :string
#  birth_date                 :date
#  birth_place                :string
#  gender                     :string
#  religion                   :string
#  marital_status             :string
#  hobby                      :string
#  stambuk                    :string
#  is_student                 :boolean          default(FALSE)
#  is_graduate                :boolean
#  is_lecture                 :boolean
#  is_staff                   :boolean
#  access_token               :string
#  nidn                       :string
#  nip                        :string
#  dummy_lecture_1_id         :bigint(8)
#  dummy_lecture_2_id         :bigint(8)
#  major_id                   :bigint(8)
#  faculty_id                 :bigint(8)
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  blangko_data               :text
#  academic_year_id           :integer
#  sortlist                   :integer
#  is_active                  :boolean          default(TRUE)
#  phone_number               :string
#  authy_id                   :string
#  last_sign_in_with_authy    :datetime
#  authy_enabled              :boolean          default(FALSE)
#  is_phone_verified          :boolean          default(FALSE)
#  is_alumni                  :boolean          default(FALSE)
#  religion_id                :bigint(8)
#  lecture_functional_type_id :bigint(8)
#  referral                   :string
#
# Indexes
#
#  index_users_on_access_token                (access_token) UNIQUE
#  index_users_on_authy_id                    (authy_id)
#  index_users_on_confirmation_token          (confirmation_token) UNIQUE
#  index_users_on_dummy_lecture_1_id          (dummy_lecture_1_id)
#  index_users_on_dummy_lecture_2_id          (dummy_lecture_2_id)
#  index_users_on_email                       (email) UNIQUE
#  index_users_on_faculty_id                  (faculty_id)
#  index_users_on_lecture_functional_type_id  (lecture_functional_type_id)
#  index_users_on_major_id                    (major_id)
#  index_users_on_nidn                        (nidn) UNIQUE
#  index_users_on_religion_id                 (religion_id)
#  index_users_on_reset_password_token        (reset_password_token) UNIQUE
#  index_users_on_stambuk                     (stambuk) UNIQUE
#  index_users_on_unlock_token                (unlock_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (lecture_functional_type_id => lecture_functional_types.id)
#  fk_rails_...  (religion_id => religions.id)
#

class Student < User
  include PgSearch::Model

  belongs_to :major, optional:true

  has_many :subject_plans
  has_many :subjects, through: :subject_plans

  has_one :student_profile, dependent: :destroy
  has_one :parent, dependent: :destroy
  has_one :alamat_tinggal, foreign_key: :user_id, class_name:"Address"
  has_one :school, dependent: :destroy

  has_one_attached :student_photo_file
  has_one_attached :kartu_keluarga_file
  has_one_attached :kartu_tanda_penduduk_file
  has_one_attached :ijazah_file

  has_many :payments, dependent: :destroy
  # validate :student_photo_file_size
  # validate :kartu_keluarga_file_size
  # validate :kartu_tanda_penduduk_file_size
  # validate :ijazah_file_size


  # has_many :documents, as: :document_file, dependent: :destroy


  # has_one :alamat_ayah, through: :parent, foreign_key: :user_id, class_name:"Address"
  # has_one :alamat_ibu, through: :parent, foreign_key: :user_id, class_name:"Address"
  # has_one :alamat_wali, through: :parent, foreign_key: :user_id, class_name:"Address"

  accepts_nested_attributes_for :student_profile, allow_destroy: true
  accepts_nested_attributes_for :parent, allow_destroy: true
  accepts_nested_attributes_for :alamat_tinggal, allow_destroy: true
  accepts_nested_attributes_for :school, allow_destroy: true

  accepts_nested_attributes_for :payments, allow_destroy: true
  # accepts_nested_attributes_for :documents

  # accepts_nested_attributes_for :alamat_ayah
  # accepts_nested_attributes_for :alamat_ibu
  # accepts_nested_attributes_for :alamat_wali

  attr_accessor :create_payment
  pg_search_scope :search, against: [:email], associated_against: {
    major: [:name],
    student_profile: [:nama, :nomor_induk_mahasiswa]
  }

  scope :begining, lambda{where("created_at > ?", "01 Jan 2020")}


  def self.referral_list
    [
      "Iskandar (085230873781)",
      "Muhammad Yusuf (081354763890)",
      "Ruth Bunga (085342293810)",
      "Ahmad Fachrial (085242813366)"
    ]
  end

  def create_payment
      @academic_year = AcademicYear.find_by(is_active: true)
      @bank = Bank.where(bank: "BRI", account_number: "034301001373303").first
      @payment = Payment.where(kind:'registrasi', academic_year_id: @academic_year.id, student_id: self.id, in_number: 350000, in_word: "Tiga Ratus Lima Puluh Ribu Rupiah", bank_id: @bank.id ).first_or_create
  end
  private

  # def student_photo_file_size
  #   # errors.add :student_photo_file, 'file terlalu besar' if student_photo_file.blob.byte_size > 2.megabytes
  #   errors[:student_photo_file] << "should be less than 5MB" if student_photo_file.blob.byte_size > 2.megabytes
  # end
  # def kartu_keluarga_file_size
  #   errors.add :kartu_keluarga_file, 'file terlalu besar' if kartu_keluarga_file.blob.byte_size > 2.megabytes
  # end
  # def kartu_tanda_penduduk_file_size
  #   errors.add :kartu_tanda_penduduk_file, 'file terlalu besar' if kartu_tanda_penduduk_file.blob.byte_size > 2.megabytes
  # end
  # def ijazah_file_size
  #   errors.add :ijazah_file, 'file terlalu besar' if ijazah_file.blob.byte_size > 2.megabytes
  # end

  def generate_access_token
    self.regenerate_access_token
  end


  def self.authenticate_student_token(student, access_token)
    if student && student.access_token == access_token
      student
    else
      nil
    end
  end
end

app/controllers/students/base_controller.rb
class Students::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :checking_student!
  before_action :checking_profile!
  private

  def checking_student!
    redirect_to send("#{user_base_url.pluralize}_dashboards_path"), flash: { error: 'Anda tidak memiliki akses ke halaman ini' } if !current_user.is_student?
  end

  def checking_profile!
    redirect_to edit_student_path(current_user), flash: { error: 'Mohon adik isi profil dan upload dokumennya terlebih dahulu' } unless current_user.is_active?
  end
end

app/controllers/students/dashboards_controller.rb
class Students::DashboardsController < Students::BaseController
  def index
    @campus_newspapers = CampusNewspaper.where(terbit: true).order("created_at desc" )
  end

end

app/views/subject_plans/form/students/teknik_pertambangan/_general_form.html.erb
<div class="card">
    <div class="card-header has-background-white-ter">
        <div class="card-header-title">
          <% if @academic_year_active.semester == "Pendek" %>
            KARTU RENCANA STUDI SEMESTER PENDEK
          <% else %>
            KARTU RENCANA STUDI
          <% end %>

        </div>

    </div>
    <div class="card-content">
      <% if @subjects.present? %>
        <%= simple_form_for @subject_plan do |f| %>
          <%= render "shared/errors", object: @subject_plan %>
          <%= f.input :student_id, as: :hidden, input_html:{value: current_user.id} %>

          <% if @academic_year_active.semester == "Pendek" %>
            <%= f.input :academic_year_id, as: :hidden, input_html:{value: @academic_year_active.id} %>
          <% else %>
            <%= f.label :academic_year, "Semester Dan Tahun Akademik" %>
            <%= f.association :academic_year, include_blank: "--Semester Dan Tahun Akademik--", collection: AcademicYear.sortir_dari_tahun_terakhir_dan_aktifnya.map{|x| ["#{x.semester} - #{x.name}", x.id]} ,wrapper: :select_bulma_small %>
          <% end %>

        <div class="columns">
          <div class="column is-7" >
            <div class="table-container"  style="height:70vh; overflow-y:auto;">
                <table class="table is-striped is-narrow is-hoverable is-bordered is-fullwidth" id="table1" value= <%= "#{check_semester}" %> >
                  <tbody>
                    <% @subjects.group_by(&:semester).each do |semester, subjects| %>
                      <tr class="is-size-7">
                          <th class="has-text-weight-light has-text-centered has-background-light" colspan="11">Semester &nbsp;<%= "#{semester}" %>
                      </tr>
                      <% subjects.each do |subject| %>
                        <tr class="is-size-7 has-text-weight-light">
                          <td class="has-text-centered"><%= check_box_tag 'subject_plan[subject_ids][]', subject.id, f.object.subjects.include?(subject), id: dom_id(subject), class:'subjectName' %></td>
                          <td class="has-text-centered" id="kodeMatakuliah"><%= subject.kode.upcase rescue nil %></td>
                          <td id="namaMatakuliah"><%= label_tag dom_id(subject),subject.matakuliah.upcase %></td>
                          <td class="has-text-centered" id="satuanKredit" value= <%= "#{subject.kredit}" %>><%= subject.kredit %></td>
                          <td class="has-text-centered"><%= subject.kategori.upcase.tr('_',' ') rescue nil %></td>
                          <td class="has-text-centered"><%= subject.khusus rescue nil %></td>
                          <td class="has-text-centered"><%= subject.tahun_berlaku rescue nil %></td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
            </div>
          </div>
          <div class="column">
              <% unless @academic_year_active.semester == 'Pendek' %>
                <table class="table is-narrow is-hoverable is-bordered is-fullwidth" id="table2">
                  <tbody>
                    <tr class="is-size-7 has-background-white-ter tabelCart">
                      <td class="has-text-centered">Kode</td>
                      <td>Matakuliah</td>
                      <td class="has-text-centered">SKS</td>
                    </tr>
                    <tr class="is-size-7" id="totalKreditMatakuliah">
                      <td></td>
                      <td >Total</td>
                      <td  class="has-text-centered" id="kreditTotal"></td>
                    </tr>
                  </tbody>
                </table>
              <% else %>
              <table class="table is-narrow is-hoverable is-bordered is-fullwidth" id="table2">
                <tbody>
                  <tr class="is-size-7 has-background-white-ter tabelCart">
                    <td class="has-text-centered">Kode</td>
                    <td>Matakuliah</td>
                    <td class="has-text-centered">SKS</td>
                    <td class="has-text-centered" id="totalBiaya">Biaya(Rp)</td>
                  </tr>

                  <tr class="is-size-7" id="totalKreditMatakuliah">
                    <td class="has-text-right is-size-7" colspan=2><strong>TOTAL</strong></td>
                    <td  class="has-text-centered" id="kreditTotal"></td>
                    <td  class="has-text-centered" id="biayaTotal"></td>
                  </tr>

                  <tr class="is-size-7 has-background-white tabelCart">
                    <td class="has-text-centered"></td>
                    <td>Biaya Daftar</td>
                    <td class="has-text-centered"></td>
                    <td class="has-text-centered" id="defaultBiaya">50000</td>
                  </tr>
                </tbody>
              </table>
              <% end %>

                <article class="message">
                  <div class="message-body">
                      <p>Catatan:</p>
                      <% unless @academic_year_active.semester == 'Pendek' %>
                        <p>- Maksimal 23 SKS</p>
                        <p>- Apabila anda tidak bisa lagi menambah matakuliah padahal total SKS masih 22, maka mohon kurangi dulu matakuliah bernilai 2 sks, kemudian berturut turut cari mata kuliah bernilai 1 SKS dan 2 SKS </p>
                      <% else %>
                        <p>- Rincian Biaya Semester Pendek:</p>
                        <p>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Biaya Daftar 50 ribu rupiah</p>
                        <p>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Per SKS 75 ribu rupiah</p>
                        <p>- Maksimal 10 SKS</p>
                        <p>- Apabila anda tidak bisa lagi menambah matakuliah padahal total SKS masih 9, maka mohon kurangi dulu matakuliah bernilai 2 sks, kemudian berturut turut cari mata kuliah bernilai 1 SKS dan 2 SKS </p>
                      <% end %>
                  </div>
                </article>
                <% if params[:action]=="edit" %>
                  <% if @subject_plan.subject_plan_file.attached? %>
                    <% if @subject_plan.subject_plan_file.representable? %>
                      <%= image_tag @subject_plan.subject_plan_file.representation(resize:"200x200") %>
                    <% end %>
                  <% end %>
                  <br />

                  KRS Semester <%= @subject_plan.academic_year.semester %>&nbsp;<%= @subject_plan.academic_year.name %><br />
                  <%= f.input :subject_plan_file, as: :file, input_html:{direct_upload: true}, wrapper: :file_bulma %>
                <% end %>
                <div class="buttons card-footer-item is-right">
                  <%= f.submit "Simpan",class: "button is-primary is-small" %>
                  <%= link_to "Index", subject_plans_path, class: "button is-danger is-small" %>
                </div>
            </div>
          </div>
          <% end %>
        <% else %>
          Maaf belum ada data
        <% end %>
      </div>

</div>

app/views/subject_plans/form/students/teknik_pertambangan/_index.html.erb
<% if current_user.student_profile.angkatan.present? %>
    <% if params[:type]=="upload_krs" %>
      <%= render partial: "subject_plans/form/#{current_user.type.downcase.pluralize}/#{current_user.major.name.downcase.gsub(' ','_')}/upload_krs", subject_plan: @subject_plan, subjects: @subjects %>
    <% else %>
      <%= render partial: "subject_plans/form/#{current_user.type.downcase.pluralize}/#{current_user.major.name.downcase.gsub(' ','_')}/general_form", subject_plan: @subject_plan, subjects: @subjects %>
    <% end %>
<% else %>
  <p>Maaf anda tidak dapat mengakses KARTU RENCANA STUDI dikarenakan :</p><br />
  <p>Nomor Induk Mahasiswa(NIM) anda salah penulisan sehingga angkatan anda tidak diketahui, pastikan NIM tanpa spasi dan tanda baca lainnya </p><br />
<% end %>

app/views/subject_plans/form/students/teknik_pertambangan/_upload_krs.html.erb
<div class="card">
    <div class="card-header has-background-white-ter">
        <div class="card-header-title">
          UPLOAD KARTU RENCANA STUDI
        </div>
        <div class="card-header-icon">

        </div>
    </div>
    <div class="card-content">
      <%= simple_form_for @subject_plan do |f| %>
        <%= render "shared/errors", object: @subject_plan %>
        KRS Semester <%= f.association :academic_year, disabled: true, collection: AcademicYear.sortir_dari_tahun_terakhir_dan_aktifnya.map{|x| ["#{x.semester} - #{x.name}", x.id]} ,wrapper: :select_bulma_small %>
        <%= f.input :subject_plan_file, as: :file, input_html:{direct_upload: true}, wrapper: :file_bulma %>
        <div class="buttons card-footer-item is-right">
          <%= f.submit "Simpan",class: "button is-primary is-small" %>
          <%= link_to "Index", subject_plans_path, class: "button is-danger is-small" %>
        </div>
      <% end %>
    </div>
</div>