config/routes.rb
Rails.application.routes.draw do
  resources :journals do
    member  do
      delete :delete_journal_file_attachment
    end
    resources :articles
  end
  resources :banks
  resources :payments do
    collection do
      put :set_approve
    end
    member do
      get :approve
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subject_plans do
    member do
      put :approve_one
      put :print
      get :print_sp
    end
    collection do
      put :set_approve
    end
  end
  get 'tahun_akademik', to: 'academics#tahun_akademik', as: :tahun_akademik
  resources :academics
  resources :candidate_students
  resources :item_accreditations
  resources :authenticate_phones, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  get 'index_skripsi', to: 'essays#index_skripsi', as: :index_skripsi
  resources :essays

  get 'index_buku', to: 'book_collections#index_buku', as: :index_buku
  resources :book_collections

  get 'index_surat', to: 'studentletters#index_surat', as: :index_surat
  resources :studentletters
  resources :jenjang_didiks

  get 'kabar_teknik', to: 'campus_newspapers#kabar_teknik', as: :kabar_teknik
  resources :campus_newspapers
  resources :landing_pages, only: [:index]



  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'verifikasi'
      post 'konfirmasi'
    end
  end

  # resources :mahasiswas do
  #   collection do
  #     put :
  #   end
  # end


  get 'daftar_calon_mahasiswa', to: 'dashboards#daftar_calon_mahasiswa', as: "daftar_calon_mahasiswa"

  get 'buat_semester_genap', to: 'academic_years#buat_semester_genap', as: "buat_semester_genap"
  get 'buat_semester_ganjil', to: 'academic_years#buat_semester_ganjil', as: "buat_semester_ganjil"

  get 'token_session', :to => "sessions#new"
  post 'token_session', :to => "sessions#create"
  get 'token_session_out', :to => "sessions#destroy"



  get 'token', to: 'graduates#token', as: "token"
  get 'wisudawan', to: 'graduates#wisudawan', as: "wisudawan"
  get 'semua', to: 'graduates#semua', as: "semua"
  get 'galeri', to: 'graduates#galeri', as: "galeri"
  get 'buku', to: 'graduates#buku', as: "buku"

  get 'index_dosen', to: 'dummy_lectures#index_dosen', as: "index_dosen"
  resources :dummy_lectures
  resources :academic_years

  get 'jadwal_kuliah', to: 'pages#jadwal_kuliah', as: "jadwal_kuliah"
  resources :schedule_subjects

  resources :subjects

  get 'info', to: 'pages#info', as: "info"

  get 'kalendar_akademik', to: 'pages#kalendar_akademik', as: "kalendar_akademik"
  get 'daftar', to: 'pages#daftar', as: "daftar"

  get 'akreditasi', to: 'item_accreditations#index', as: "akreditasi"

  concern :documentable do
    resources :documents, only: [:new, :create, :edit, :update, :destroy]
  end
  concern :dashboardtable do
    # authenticated :user do
    #   root to: 'dashboards#index'#, as: :authenticated_root
      resources :dashboards, only: [:index]
    # end
  end

  namespace :juniors do
    concerns :dashboardtable
  end

  namespace :staffs do
    concerns :dashboardtable
  end

  namespace :students do
    concerns :dashboardtable
  end

  namespace :lectures do
    concerns :dashboardtable
  end

  namespace :admins do
    concerns :dashboardtable
  end

  resources :lectures, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :profile
      get :educations
      get :training_professionals
      get :teachings
      get :materials
      get :researchs
      get :scientifics
      get :papers
      get :reviewers
      get :conferences
      get :professionals
      get :positions
      get :student_organizations
      get :scientific_organizations
      get :appreciations
      put :print
    end
      resources :lecture_education_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :professional_trainings, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_teaching_materials, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_researches, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientific_works, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_papers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_reviewers, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_conferences, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_position_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_professional_activities, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_student_organization_histories, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_appreciations, only:[:index, :new, :create, :edit, :update, :destroy]
      resources :lecture_scientist_organizations, only:[:index, :new, :create, :edit, :update, :destroy]
  end

  resources :students, only:[:index, :show, :edit, :update, :destroy], concerns: :documentable do
    member do
      get :edit_formulir
      patch :make
      get :delete_file
      # p :print
      get :print_blanko
      get :print_formulir
      put :active_one
    end
    collection do
      get :studyplans
      put :active_all
    end

    resources :payments, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        get :print
        get :print_registrasi
        get :letter
      end
    end
  end

  resources :staffs , only:[:index, :show, :new, :create,  :edit, :update, :destroy ] do
    member do
      get :profile
    end
  end


  resources :lecture_lists
  resources :graduates do
    collection  do
      put :update_all
      post :import
    end
    member do
      get :download
      get :send_token_email
      get :formulir_wisuda
      get :edit_formulir
      patch :update_access_token, to:'graduates#update_access_token'
    end
  end

  resources :mahasiswas do
    member do
      get 'biodata', to: 'mahasiswas#biodata', as: :biodata
      get 'edit_biodata', to: 'mahasiswas#edit_biodata', as: :edit_biodata
    end
    collection do
      put :activate
    end
    resources :documents

  end

  get 'index_mahasiswa', to: 'mahasiswa_profiles#index_mahasiswa', as: :index_mahasiswa
  resources :mahasiswa_profiles

  root to: 'pages#index'

  devise_for :users, controllers: {
        passwords: 'users/passwords',
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'}

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage
    # for speed, so on the client side we'll upload files to our app.
    mount Shrine.upload_endpoint(:cache) => "/upload"
  end
end

app/controllers/subject_plans_controller.rb
class SubjectPlansController < ApplicationController
  before_action :authenticate_user!
  # before_action :authenticate_staff, except: [:index]
  before_action :authenticate_student, only: [:print]
  before_action :set_subject_plan, only: [:show, :edit, :update, :destroy, :approve_one, :print]
  before_action :set_semester_active, only: [:index, :show, :new, :edit, :destroy, :approve_one, :print, :print_sp]
  before_action :check_if_approved?, only:[:edit, :destroy]

  def check_if_approved?
    @subject_plan = SubjectPlan.find(params[:id])
    if current_user.is_student?
      redirect_to subject_plans_path, alert: "KRS sudah tidak bisa lagi di edit karena sudah diperiksa bagian akademik" if @subject_plan.is_approved?
    end
  end

  def authenticate_student
    if current_user.is_student?
      @subject_plan = SubjectPlan.find(params[:id])
      redirect_to token_session_path(subject_plan_id: @subject_plan.id), notice: "Masukkan Kode Token Terlebih Dahulu" if current_authenticate_student.nil?
    end
  end

  def authenticate_staff
    if current_user.is_staff?
      redirect_to token_session_path, notice: "Masukkan Kode Token Terlebih Dahulu" if current_authenticate_staff.nil?
    end
  end

  def index
    @subject_plan_semester_pendek = SubjectPlan.where(student_id: current_user.id, academic_year_id: current_academic_year.id).first
    if current_user.is_student?
      @subject_plans = SubjectPlan.includes(:academic_year, student:[:student_profile, major: :faculty]).where(student_id: current_user.id).order("academic_years.name desc").order("academic_years.semester desc").page(params[:page]).per(10)
    elsif current_user.is_staff?
      @academic_year_active = AcademicYear.where(is_active: true).first
      @academic_years = AcademicYear.order("created_at desc")
      @subject_plans = SubjectPlan.includes(:academic_year, student:[:student_profile, major: :faculty]).order("academic_years.name desc").order("academic_years.semester desc").page(params[:page]).per(10)
    elsif current_user.is_lecture?
      @academic_year_active = AcademicYear.where(is_active: true).first
      @academic_years = AcademicYear.order("created_at desc")
      @subject_plans = SubjectPlan.includes(:academic_year, student:[:student_profile, major: :faculty]).order("academic_years.name desc").order("academic_years.semester desc").page(params[:page]).per(10)
    end
    @subject_plans = @subject_plans.search(params[:search]) if params[:search].present?
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new

    if current_user.is_student?
      if current_user.student_profile.angkatan.to_i >= 2018
        # if @academic_year_active.semester == 'ganjil'
        #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["1","3","5","7"]).where.not(tahun_berlaku: "2014").order(:semester).order(:matakuliah).order(:kategori)
        # elsif @academic_year_active.semester == 'genap'
        #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["2","4","6","8"]).where.not(tahun_berlaku: "2014").order(:semester).order(:matakuliah).order(:kategori)
        # elsif @academic_year_active.semester == 'pendek'
        #   @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2014").order(:semester).order(:matakuliah).order(:kategori)
        # end
        @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2014").order(:semester).order(:matakuliah).order(:kategori)

      else
        if current_user.student_profile.konsentrasi == "tambang umum"
          # if @academic_year_active.semester == 'ganjil'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["1","3","5","7"]).where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi").order(:semester).order(:matakuliah).order(:kategori)
          # elsif @academic_year_active.semester == 'genap'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["2","4","6","8"]).where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi").order(:semester).order(:matakuliah).order(:kategori)
          # elsif @academic_year_active.semester == 'pendek'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi").order(:semester).order(:matakuliah).order(:kategori)
          # end
          @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi").order(:semester).order(:matakuliah).order(:kategori)
        else
          # if @academic_year_active.semester == 'ganjil'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["1","3","5","7"]).where.not(tahun_berlaku: "2018", khusus:"tambang umum").order(:semester).order(:matakuliah).order(:kategori)
          # elsif @academic_year_active.semester == 'genap'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)", semester:["2","4","6","8"]).where.not(tahun_berlaku: "2018", khusus:"tambang umum").order(:semester).order(:matakuliah).order(:kategori)
          # elsif @academic_year_active.semester == 'pendek'
          #   @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2018", khusus:"tambang umum").order(:semester).order(:matakuliah).order(:kategori)
          # end
          @subjects = Subject.where("'pertambangan' = ANY (tags)").where.not(tahun_berlaku: "2018", khusus:"tambang umum").order(:semester).order(:matakuliah).order(:kategori)
        end
      end
    end
    @subject_plan = SubjectPlan.new
  end

  def create
    @subject_plan = SubjectPlan.new(subject_plans_params)
    if @subject_plan.save
      redirect_to @subject_plan, notice: 'KRS berhasil dibuat.'
    else
      flash[:danger] = 'KRS gagal disimpan'
      render :new
    end
  end

  def edit
    if current_user.is_student?
      @student = current_user.id
      @subjects = Subject.where("'#{SubjectPlan.tag_params_major(current_user.major.name)}' = ANY (tags)").order(:semester).includes(:subject_plans).order(:matakuliah).order(:kategori)
      if current_user.student_profile.angkatan.to_i >= 2018
        @subjects = @subjects.where.not(tahun_berlaku: "2014")
      else
        if current_user.student_profile.konsentrasi == "tambang umum"
          @subjects = @subjects.where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi")
        else
          @subjects = @subjects.where.not(tahun_berlaku: "2018", khusus:"tambang umum")
        end
      end
    elsif current_user.is_staff?
      @student = @subject_plan.student
      @subjects = Subject.where("'#{SubjectPlan.tag_params_major(@student.major.name)}' = ANY (tags)").order(:semester).order(:matakuliah).order(:kategori)
      if @student.student_profile.angkatan.to_i >= 2018
        @subjects = @subjects.where.not(tahun_berlaku: "2014")
      else
        if @student.student_profile.konsentrasi == "tambang umum"
          @subjects = @subjects.where.not(tahun_berlaku: "2018", khusus:"tambang eksplorasi")
        else
          @subjects = @subjects.where.not(tahun_berlaku: "2018", khusus:"tambang umum")
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @subject_plan.update!(subject_plans_params)
        format.html {redirect_to subject_plan_path(@subject_plan), notice: "KRS berhasil diupdate"}
      else
        flash[:danger] = 'KRS gagal disimpan'
        format.html {render :edit}
      end
    end
  end

  def show
    @academic_year = AcademicYear.where(is_active: true).first
    @subject_plan = SubjectPlan.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def print
    respond_to do |format|
      @subject_plan = SubjectPlan.find(params[:id])
      @subjects = @subject_plan.subjects.order(:semester).order(:matakuliah)
      if @subject_plan.save
        @subject_plan.update(is_printed: true)
        format.html
        format.pdf do
          render pdf: "KRS #{@subject_plan.student.student_profile.nama} #{@subject_plan.student.student_profile.nomor_induk_mahasiswa}",
          template: "subject_plans/print_pdf.html.erb",
          layout: 'pdf.html',
          locals: {:subjects => @subjects},
          page_size: 'A4'
        end
      end
    end
  end

  def print_sp
    respond_to do |format|
      @subject_plan = SubjectPlan.find(params[:id])
      @subjects = @subject_plan.subjects.order(:semester).order(:matakuliah)
      if @subject_plan.save
        @subject_plan.update(is_printed: true)
        format.html
        format.pdf do
          render pdf: "KRS #{@subject_plan.student.student_profile.nama} #{@subject_plan.student.student_profile.nomor_induk_mahasiswa}",
          template: "subject_plans/print_sp_pdf.html.erb",
          layout: 'pdf.html',
          locals: {:subjects => @subjects},
          page_size: 'A4'
        end
      end
    end
  end

  def destroy
    @subject_plan.destroy
    redirect_to subject_plans_path, notice: "Data KRS berhasil dihapus"
    respond_to do |format|
      format.html
    end
  end

  def approve_one
    @student = @subject_plan.student
    @student.regenerate_access_token
    if @subject_plan.is_approved == false
      @subject_plan.update(is_approved: true)
      SubjectPlanMailer.send_token_payment(@student).deliver_now
      redirect_to subject_plans_path, notice: "Data KRS diterima"

    elsif @subject_plan.is_approved == true
      @subject_plan.update(is_approved: false)
      redirect_to subject_plans_path, alert: "Data KRS ditolak"
    end

  end

  def set_approve
    if params[:commit] == "ACC"
      @subject_plans = SubjectPlan.where(id: params[:subject_plan_id]).update_all(is_approved: true)
      redirect_to subject_plans_path, notice: "Data KRS diterima"
    elsif params[:commit] == "Tidak ACC"
      @subject_plans = SubjectPlan.where(id: params[:subject_plan_id]).update_all(is_approved: false)

app/views/subject_plans/index/_lectures.html.erb
<div class="card">
    <div class="card-header has-background-white-ter">
      <div class="card-header-title">
          DAFTAR KARTU RENCANA STUDI
      </div>
    </div>
    <div class="card-content" id="tableIndex">
      <% if @subject_plans.present? %>
        <%= render partial: "subject_plans/index/table_#{current_user.type.downcase.pluralize}" %>
      <% else %>
          Maaf data belum ada
      <% end %>
    </div>
</div>

app/views/subject_plans/index/_staffs.html.erb
<div class="card">
    <div class="card-header has-background-white-ter">
      <div class="card-header-title">
          DAFTAR KARTU RENCANA STUDI
      </div>
      <div class="card-header-icon">
        <%= form_tag subject_plans_path, method: :get do %>
            <div class="field has-addons">
              <div class="control">
                <%= text_field_tag :search, params[:search], placeholder: "--cari kata--", class: "input is-small is-fullwidth"  %>
              </div>
              <div class="control">
                <%= submit_tag "Cari", name:nil, class: "button is-success is-small" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <div class="card-content" id="tableIndex">
      <% if @subject_plans.present? %>
        <%= render partial: "subject_plans/index/table_#{current_user.type.downcase.pluralize}" %>
      <% else %>
          Maaf data belum ada
      <% end %>
    </div>
</div>

app/views/subject_plans/index/_students.html.erb
<div class="card">
    <div class="card-header has-background-white-ter">
      <div class="card-header-title">
          DAFTAR KARTU RENCANA STUDI
      </div>
      <% unless current_academic_year.semester == "Pendek" && @subject_plan_semester_pendek.present? %>
      <div class="card-header-icon">
          <%= link_to "Tambah", new_subject_plan_path, class:'button is-success is-small' %>
      </div>
      <% end %>
    </div>
    <div class="card-content" id="tableIndex" >
      <% if @subject_plans.present? %>
        <%= render partial: "subject_plans/index/table_#{current_user.type.downcase.pluralize}" %>
      <% else %>
          Maaf data belum ada
      <% end %>
    </div>
</div>

app/views/subject_plans/index/_table_staffs.html.erb
<div class="level">
    <div class="level-right">
      <%= paginate @subject_plans, remote: true %>
    </div>
</div>
<div class="table-container">
  <table class="table is-fullwidth is-hoverable is-striped is-narrow is-bordered">
    <thead>
      <tr>
          <th class="has-text-centered">Nama</th>
          <th class="has-text-centered">NIM</th>
          <th class="has-text-centered">Prodi</th>
          <th class="has-text-centered">Semester</th>
          <th class="has-text-centered">Tahun Akademik</th>
          <th class="has-text-centered">Bayar</th>
          <th class="has-text-centered">IPK</th>
          <th class="has-text-centered">SKS</th>
          <th class="has-text-centered">Upload</th>
          <th colspan="2" class="has-text-centered"></th>
          <% if current_user.email =="kingmalprax@gmail.com" %>
          <th class="has-text-centered"></th>
          <% end %>
      </tr>
    </thead>
    <tbody>
      <% @subject_plans.each_with_index do |subject_plan| %>
        <tr>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to subject_plan.student.student_profile.nama.titleize, subject_plan  rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.student.student_profile.nomor_induk_mahasiswa rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.student.major.name rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.academic_year.semester rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to subject_plan.academic_year.name, subject_plan rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.student.payments.find_by_academic_year_id(subject_plan.academic_year_id).is_approved? ? icon_check('') : icon_times('') rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;"></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.subjects.sum(:kredit) rescue nil %></td>
          <td class="has-text-centered" style="vertical-align:middle;">
            <% if subject_plan.subject_plan_file.attached? %>
                <% if subject_plan.subject_plan_file.representable? %>
                  <%= link_to image_tag(subject_plan.subject_plan_file.representation(resize: "80x50")), rails_blob_path(subject_plan.subject_plan_file, disposition: "attachment") %>
                <% end %>
            <% else %>
                <%= link_to icon_upload(''), edit_subject_plan_path(subject_plan, type:"upload_krs") %>
            <% end %>
          </td>
          <% if current_user.email == "kingmalprax@gmail.com" || "bungahati.2310@gmail.com" %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= check_approve_with_link(subject_plan, approve_one_subject_plan_path(subject_plan), :put)  %></td>
          <% else %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= check_approve(subject_plan)  %></td>
          <% end %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to_if subject_plan.is_approved?, icon_print(''), print_subject_plan_path(subject_plan, format: :pdf), target: :_blank, class: "button is-danger is-small" %></td>
          <!-- <td class="has-text-centered" style="vertical-align:middle;"><%#= link_to icon_edit(''), edit_subject_plan_path(subject_plan) %></td> -->
          <% if current_user.email =="kingmalprax@gmail.com" %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to icon_delete(''), subject_plan_path(subject_plan), method: :delete, data:{confirm:"Anda yakin hapus?"} %></td>
          <% end %>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>
<p>Catatan:</p>
<p>- Icon <%= icon_print('') %> berubah menjadi <span class="button is-danger is-small"><%= icon_print_button('') %></span> untuk memprint, apabila sudah diperiksa dan dibetulkan oleh bagian akademik</p>
<p>- Status  <%= icon_times('') %> berubah menjadi <%= icon_check('') %> juga apabila sudah diperiksa dan dibetulkan oleh bagian akademik</p>
<p>- Mohon bersabar menunggu hingga status dan ikon nya berubah</p>
<p>- Info perubahan status dapat dicek secara berkala, juga melalui email anda</p>
<p>- Cetak dikertas ukuran A4 tanpa dipotong</p>
<p>- Jangan lupa bubuhkan tanda tangan anda dan penasehat akademik(yang mewakili dari kepala Biro Akademik dan Administrasi Fakultas)</p>
<p>- Scan dan segera upload filenya sesuai dengan data yang dibuat disini </p>
<p>- Klik gambar/foto blanko jika anda ingin mendownload</p>

app/views/subject_plans/index/_table_students.html.erb
<div class="level">
    <div class="level-right">
      <%= paginate @subject_plans, remote: true %>
    </div>
</div>
<div class="table-container" >
  <table class="table is-fullwidth is-hoverable is-striped is-narrow is-bordered">
    <thead>
      <tr>
          <th class="has-text-centered">Semester</th>
          <th class="has-text-centered">Tahun Akademik</th>
          <th class="has-text-centered">SKS</th>
          <th>Penasehat</th>
          <th class="has-text-centered">Upload</th>
          <th class="has-text-centered">Status</th>
          <th colspan="3" class="has-text-centered"></th>
      </tr>
    </thead>
    <tbody>
      <% @subject_plans.each_with_index do |subject_plan| %>
        <tr>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to subject_plan.academic_year.semester, subject_plan %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.academic_year.name %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= subject_plan.subjects.sum(:kredit) %></td>
          <td style="vertical-align:middle;"><%= subject_plan.penasehat_akademik %></td>
          <td class="has-text-centered" style="vertical-align:middle;">
            <% if subject_plan.subject_plan_file.attached? %>
                <% if subject_plan.subject_plan_file.representable? %>
                  <%= link_to image_tag(subject_plan.subject_plan_file.representation(resize: "80x50")), rails_blob_path(subject_plan.subject_plan_file, disposition: "attachment") %>
                <% end %>
            <% else %>
                <%= link_to icon_upload(''), edit_subject_plan_path(subject_plan, type:"upload_krs") %>
            <% end %>
          </td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= check_approve(subject_plan) %></td>
          <% unless @academic_year_active.semester == "Pendek" %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to_if subject_plan.is_approved?, icon_print(''), print_subject_plan_path(subject_plan, format: :pdf), target: :_blank, class: "button is-danger is-small" %></td>
          <% else %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to icon_print(''), print_sp_subject_plan_path(subject_plan, format: :pdf), target: :_blank, class: "button is-danger is-small" %></td>
          <% end %>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to_if subject_plan.is_not_approved?, icon_edit(''), edit_subject_plan_path(subject_plan) %></td>
          <td class="has-text-centered" style="vertical-align:middle;"><%= link_to_if subject_plan.is_not_approved?, icon_delete(''), subject_plan_path(subject_plan), method: :delete, data:{confirm:"Anda yakin hapus?"} %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>
<p>Catatan:</p>
<p>- Icon <%= icon_print('') %> berubah menjadi <span class="button is-danger is-small"><%= icon_print_button('') %></span> untuk memprint, apabila sudah diperiksa dan dibetulkan oleh bagian akademik</p>
<p>- Status  <%= icon_times('') %> berubah menjadi <%= icon_check('') %> juga apabila sudah diperiksa dan dibetulkan oleh bagian akademik</p>
<p>- Mohon bersabar menunggu hingga status dan ikon nya berubah</p>
<p>- Info perubahan status dapat dicek secara berkala, juga melalui email anda</p>
<p>- Cetak dikertas ukuran A4 tanpa dipotong</p>
<p>- Jangan lupa bubuhkan tanda tangan anda dan penasehat akademik(yang mewakili dari kepala Biro Akademik dan Administrasi Fakultas)</p>
<p>- Scan dan segera upload filenya sesuai dengan data yang dibuat disini </p>
<p>- Klik gambar/foto blanko jika anda ingin mendownload</p>